# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -r examples/test_requirements.txt
        pip install coverage codecov
        python setup.py install
    - name: Install redis
      run: |
        sudo apt update
        sudo apt install redis -y
        pip install redis
    - name: Install gcc
      run: |
        sudo apt update
        sudo apt install gcc -y
        python setup.py install
    - name: Test all
      run: |
        redis-server --daemonize yes
        cp examples/img.jpeg img.jpeg
        coverage run -p examples/example1.py
        coverage run -p examples/example_redis.py
        coverage run -p examples/example_save.py
        coverage run -p examples/example_img_hash.py
        coverage run -p examples/example_img_hist.py
        coverage run -p examples/example_simhash.py
        coverage run -p examples/example_simhash2.py
        coverage run -p examples/example_fuzzy_hash.py
    - name: Cov
      run: |
        coverage combine
        codecov
